### ISSUE TITLE
Polar Connect Isn't Working for me

### ISSUE THREAD

**Issue by iamef** [burtonator/polar-connect-anki#1]
I tried different versions of Anki and disabled other addons, but am still unable to get Polar Connect to work. 

Thanks! :)

Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-05 13:35:51
Add-ons possibly involved: ⁨Polar Connect - PDF and Incremental Reading with Anki Sync⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/work/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 309, in advance
    self.server.advance()
  File "/Users/work/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 217, in advance
    self.advanceClients()
  File "/Users/work/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 232, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/work/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 232, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/work/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 139, in advance
    self.writeBuff += self.handler(req)
  File "/Users/work/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 251, in handlerWrapper
    body = makeBytes(json.dumps(self.handler(params)))
  File "json/__init__.py", line 231, in dumps
  File "json/encoder.py", line 199, in encode
  File "json/encoder.py", line 257, in iterencode
  File "json/encoder.py", line 179, in default
TypeError: Object of type RepeatedScalarContainer is not JSON serializable

**Comment by roboticsdude60** [comment]
I assume I have the same issue. Could it be a problem with our version of Python?

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (arch-linux-2.1.26-1) Python 3.8.3 Qt 5.14.2 PyQt 5.14.2
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons, last update check: 2020-06-08 23:44:46
Add-ons possibly involved: ⁨Polar Connect - PDF and Incremental Reading with Anki Sync⁩

Caught exception:
Traceback (most recent call last):
  File "/home/joe/.local/share/Anki2/addons21/734898866/__init__.py", line 309, in advance
    self.server.advance()
  File "/home/joe/.local/share/Anki2/addons21/734898866/__init__.py", line 217, in advance
    self.advanceClients()
  File "/home/joe/.local/share/Anki2/addons21/734898866/__init__.py", line 232, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/home/joe/.local/share/Anki2/addons21/734898866/__init__.py", line 232, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/home/joe/.local/share/Anki2/addons21/734898866/__init__.py", line 139, in advance
    self.writeBuff += self.handler(req)
  File "/home/joe/.local/share/Anki2/addons21/734898866/__init__.py", line 251, in handlerWrapper
    body = makeBytes(json.dumps(self.handler(params)))
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RepeatedScalarContainer is not JSON serializable

**Comment by roboticsdude60** [comment]
#2 looks like it is supposed to fix this when it gets merged
